spring.application.name=order-service

# This will fetch the configuration from config server which is running on localhost:8888 and it will look for
# inventory-service.properties file in config server and fetch the configuration from there
# and this configs are on git
spring.config.import=configserver:http://localhost:8888
# first it will look for default profile and will try to fetch its configs then it will override it with the active profile configs
# if there is any and if there is no active profile then it will use the default profile configs
spring.profiles.active=dev


# this below configs is now on github with using config server it will be fetched from there
## Server configuration
#server.servlet.context-path=/orders
#server.port=9020
#
##DB Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=create-drop
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
##spring.jpa.defer-datasource-initialization=true
##spring.sql.init.mode=always
##spring.sql.init.schema-locations=classpath:data.sql
#
## Eureka Client configuration
## To register with Eureka Server
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/