spring.application.name=discovery-service

# This will fetch the configuration from config server which is running on localhost:8888 and it will look for
# inventory-service.properties file in config server and fetch the configuration from there
# and this configs are on git
spring.config.import=configserver:http://localhost:8888

# This below configs is now on github with using config server it will be fetched from there
##Eureka Server configuration
## To not make it as client of itself
#eureka.client.register-with-eureka=false
## To not fetch registry information from itself
#eureka.client.fetch-registry=false
#server.port=8761