spring.application.name=discovery-service

#Eureka Server configuration
# To not make it as client of itself
eureka.client.register-with-eureka=false
# To not fetch registry information from itself
eureka.client.fetch-registry=false
server.port=8761