spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chinmayk12/ecommerce-microservice-config-server
          username: Chinmayk12
          password : ${GITHUB_TOKEN} # We use environment variable to store the password for security reasons. You can set this environment variable in your system or IDE.
          default-label: main

server:
  port: 8888

# Eureka client configuration. We disable registration because the Config Server
# starts FIRST, before Eureka is even running.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/











